[tool.ruff]
# 行の長さを79文字に制限
line-length = 79

# Python互換性の設定
target-version = "py310"

[tool.ruff.lint]
# Lintの基本ルールセット
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort
]

[tool.ruff.format]
# 引用符のスタイル: ダブルクォート
quote-style = "double"
# インデントはスペース4つ
indent-style = "space"
